AllCops:
  Exclude:
    - 'tmp'
    - 'vendor/**/*'
  TargetRubyVersion: 2.3

Layout/LineLength:
  Description: 'Limit lines to a more generous 180 characters.'
  Enabled: true
  Max: 180

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - '*.gemspec'
    - 'spec/*.rb'

Metrics/ClassLength:
  Max: 300

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Max: 155

Style/Documentation:
  Enabled: false

# Future Cops - 1.0
Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true
